### ISSUE TITLE
Warning about undo-outer-limit

### ISSUE THREAD

**Issue by alanpearce** [Bruce-Connor/paradox#16]
I usually receive these warnings after running `paradox-list-packages` (yes, two per run), but I'm not sure why paradox would be executing any undoable operations. I realise there are two workarounds explained in the messages, but I don't normally receive this warning, so I don't really want to increase the limit or hide the message.

Emacs 24.3.1, both on Arch GNU/Linux and OSX (via [emacs-mac-port](railwaycat/emacs-mac-port)).

> Warning (undo): Buffer `*Packages*' undo info was 13042138 bytes long.
The undo info was discarded because it exceeded `undo-outer-limit'.

> This is normal if you executed a command that made a huge change
to the buffer.  In that case, to prevent similar problems in the
future, set `undo-outer-limit' to a value that is large enough to
cover the maximum size of normal changes you expect a single
command to make, but not so large that it might exceed the
maximum memory allotted to Emacs.

> If you did not execute any such command, the situation is
probably due to a bug and you should report it.

> You can disable the popping up of this buffer by adding the entry
(undo discard-info) to the user option `warning-suppress-types',
which is defined in the `warnings' library.

>Warning (undo): Buffer `*Packages*' undo info was 13098490 bytes long.
The undo info was discarded because it exceeded `undo-outer-limit'.

> This is normal if you executed a command that made a huge change
to the buffer.  In that case, to prevent similar problems in the
future, set `undo-outer-limit' to a value that is large enough to
cover the maximum size of normal changes you expect a single
command to make, but not so large that it might exceed the
maximum memory allotted to Emacs.

> If you did not execute any such command, the situation is
probably due to a bug and you should report it.

> You can disable the popping up of this buffer by adding the entry
(undo discard-info) to the user option `warning-suppress-types',
which is defined in the `warnings' library.

**Comment by Bruce-Connor** [comment]
Hi @alanpearce, did this issue resolve itself for you? 
Is it still happening?

**Comment by alanpearce** [comment]
Seems to have resolved itself! Works for me.

**Comment by Bruce-Connor** [comment]
Great!
