### ISSUE TITLE
-upgrade-packages: List upgraded packages

### ISSUE THREAD

**Issue by mwfogleman** [Bruce-Connor/paradox#31]
Currently, the message that is posted when paradox-upgrade-packages finishes is:
[Paradox] Upgrade finished.

Could you append which packages were upgraded?

**Comment by Bruce-Connor** [comment]
This has now been implemented in the `paradox--report` function.
This function prints a full report to the `*Paradox Report*` buffer. It also displays the buffer if the upgrade was performed with the `noquery` argument (which means the user probably didn't see the list of packages being upgraded) (it also what happens with the `upgrade-packages` command).

Any suggestions on how to improve it are very welcome.
