### ISSUE TITLE
Feature request - create commit when automatically upgrading

### ISSUE THREAD

**Issue by peterhoeg** [Bruce-Connor/paradox#32]
Disqus just ate the comment I left on endlessparens, so I'm opening an issue instead.

It would be super neat if in connection with auto upgrades, paradox would create commits for each updated package.

Example:

Paradox upgrades package foo from 1.1 to 1.2 which should create a commit like this:
`foo: version 1.2 (was: 1.1)`

And there would of course be lots of bonus internet points if dependencies were handled the same way.

**Comment by peterhoeg** [comment]
Sorry, I should have made that clearer.
What I meant is, that as I keep the entire emacs config in a git repository.

**Comment by Bruce-Connor** [comment]
Ah, I see what you meant then. 

Here are my thoughts:
- Creating commits for a repo at every upgrade is a very narrow use-case, and it would require much more information and a lot of work.
- What I *can* do is implements some hooks on Paradox. These hooks would be run before and after each upgrade, so you could easily use them to create commits for your git repo.

**Comment by peterhoeg** [comment]
The hooks would be great. Would you be willing to accept code that then uses those hooks to handle the commits?

**Comment by Bruce-Connor** [comment]
Yes, but it may take me a week or two to get this hooks going.

**Comment by Bruce-Connor** [comment]
Ok, the hook has been implemented in the latest push.
Feel free to write up a function (and a `defcustom` or two) that creates a commit after an upgrade.
