### ISSUE TITLE
Can't clear keyword filter

### ISSUE THREAD

**Issue by jguenther** [Bruce-Connor/paradox#33]
Great package!

Perhaps I'm missing something but there doesn't seem to be a way to clear the current keyword filter without killing the paradox package list buffer. Setting the filter to the empty string gives an empty package list.

**Comment by Bruce-Connor** [comment]
It should be enough to hit q. Doesn't that work for you?

**Comment by jguenther** [comment]
Whoops. It seems I *was* missing something -- that works just fine.

Perhaps a dedicated `clear filter' function would be useful? Judging from the name, `paradox-quit-and-close' didn't seem to me like it would clear the filter and leave the packages buffer open -- I assumed that it would just kill the buffer. Or perhaps activating a filter could open a new buffer with the filtered package list, and `q' there would kill that buffer?

An entry in the Paradox menu to clear the filter might be useful as well. I probably won't have time this week but I can see about submitting a PR when I get some free time. What do you think?

**Comment by Bruce-Connor** [comment]
Oh, that sounds great. I'd be happy to accept that PR.

**Comment by Bruce-Connor** [comment]
You're also not the first one to ask me about this. So a second function with a better name is definitely in order.

**Comment by Bruce-Connor** [comment]
OK, I've defined a new command specifically for clearing the filter. I didn't even need to write one, it is just an alias to another command.

`q` is now always quits the window, even with a filter.
