### ISSUE TITLE
Invalid date error when listing commits for some packages

### ISSUE THREAD

**Issue by colbell** [Bruce-Connor/paradox#34]
When listing commits for the `ace-link` package from within Paradox I get an Invalid date error.

    Debugger entered--Lisp error: (error "Invalid date: 20141230T 7: 8")
      signal(error ("Invalid date: 20141230T 7: 8"))
      error("Invalid date: %s" "20141230T 7: 8")
      byte-code("\300\301\302\217\207" [nil (byte-code "\301\302\303\304!!\"\207" [date apply encode-time parse-time-string timezone-make-date-arpa-standard] 5) ((error (error "Invalid date: %s" date)))] 3)
      date-to-time("20141230T 7: 8")
      paradox--get-installed-version(ace-link)
      paradox-menu-view-commit-list(nil)
      call-interactively(paradox-menu-view-commit-list nil nil)
      command-execute(paradox-menu-view-commit-list)

It works for  most packages but fails for `ace-link`. The version of ace-link currently installed is `20141230.708`.

It also fails on `helm` with version `20150107.2203`.

**Comment by colbell** [comment]
I've just upgraded `ace-link` to the latest version `20150108.1324` and no longer have the problem with that package but still have it with `helm`

    Debugger entered--Lisp error: (error "Invalid date: 20150107T22: 3")
      signal(error ("Invalid date: 20150107T22: 3"))
      error("Invalid date: %s" "20150107T22: 3")
      byte-code("\300\301\302\217\207" [nil (byte-code "\301\302\303\304!!\"\207" [date apply encode-time parse-time-string timezone-make-date-arpa-standard] 5) ((error (error "Invalid date: %s" date)))] 3)
      date-to-time("20150107T22: 3")
      paradox--get-installed-version(helm)
      paradox-menu-view-commit-list(nil)
      call-interactively(paradox-menu-view-commit-list nil nil)
      command-execute(paradox-menu-view-commit-list)

**Comment by Bruce-Connor** [comment]
Thanks for filing this, I think I know why it's happening.

**Comment by Bruce-Connor** [comment]
It should be fixed now. Let me know if it happens again.

**Comment by colbell** [comment]
Yep, fixed.

Thanks.
