### ISSUE TITLE
Seeing hangs on paradox-list-packages

### ISSUE THREAD

**Issue by stsquad** [Bruce-Connor/paradox#36]
I see a message in the minbuffer that the last thing was:

"Contacting host: melpa.org:80"

However even with debug-on-quit enabled I have no idea where it was when I finally hit Ctrl-g in frustration.

**Comment by Bruce-Connor** [comment]
Does it hang if you don't use paradox? (calling `paradox-disable` then `list-packages`)

**Comment by stsquad** [comment]
Something is wrong because "paradox-disable" is not defined.

**Comment by Bruce-Connor** [comment]
Ok, then something really is wrong. 

1. Did you install from Melpa? 
2. What are your Emacs and Paradox version?
3. What happens if you start emacs with `emacs -Q`, then just invoke `M-x package-initialize` and `M-x paradox-list-packages`?

**Comment by stsquad** [comment]
1. Yes it a MELPA based set-up
2.
  - "GNU Emacs 24.4.51.10 (x86_64-unknown-linux-gnu, X toolkit, Xaw3d scroll bars)
  - paradox-20150110.1628
3. That works, but paradox-disable isn't available until your first run

I'm wondering if the github integration is what's taking the time. Is it possible to disable that?

**Comment by Bruce-Connor** [comment]
> That works, but paradox-disable isn't available until your first run

Ok, then it's not so bad. `paradox-disable` is only supposed to be available after Paradoxhas been loaded. 

I had told you to use `paradox-disable` just to make sure you were loading the regular package menu. If you start a fresh Emacs instance (where you haven't called `paradox-list-packages`) then just doing good old `list-packages` should be enough to get you the regular package menu.

What about the hang? Did Emacs hang when you ran `paradox-list-packages` from `emacs -Q`?

>I'm wondering if the github integration is what's taking the time. Is it possible to disable that?

Yes, you can disable it by setting `paradox-github-token` to `t`. Let me know if that makes a difference.

**Comment by Bruce-Connor** [comment]
Did you manage to turn off github integration? Did it work?

**Comment by stsquad** [comment]
I need to test back on my work machine on Monday. But I suspect the github integration could be the culprit. Does it do a request for every possible package or just every installed package?

**Comment by Bruce-Connor** [comment]
Neither. 
It does a single request to get your entire list of starred repos. 

That said, it could be the culprit. It uses curl instead of using the url package, and there have been reports of it getting on people's workplace firewall.

**Comment by Bruce-Connor** [comment]
*getting stuck*

**Comment by stsquad** [comment]
OK you can close this issue. Once I removed the SSL org-mode repo (https://orgmode.org/elpa/) from my package-archives it returned to it's normal speed. Sorry about the noise. It just wasn't very clear when quitting what was holding everything up.

**Comment by Bruce-Connor** [comment]
No problem, glad it's solved.
