### ISSUE TITLE
Error encoding buffer *temp*

### ISSUE THREAD

**Issue by joca-bt** [Bruce-Connor/paradox#40]
Recently, whenever I do ```paradox-list-packages``` I get the error

    These default coding systems were tried to encode text in the buffer ` *temp*':
      (iso-latin-1-dos (3242 . 37326) (3243 . 40165))
    However, each of them encountered characters it couldn't encode:
      iso-latin-1-dos cannot encode these: 野 鳥

as the Paradox buffer is not in UTF8.

**Comment by Bruce-Connor** [comment]
OK, thanks for reporting this. Could you check whether this also happens with the regular package-menu?

Just restart your emacs and call `list-packages` (instead of `paradox-list-packages`).

**Comment by joca-bt** [comment]
It does!

**Comment by Bruce-Connor** [comment]
Ok, then I think we ought to report that bug straight to the mothership. :-)

**Comment by joca-bt** [comment]
Indeed! A shame I can't just GitHub Issue open it :(

**Comment by Bruce-Connor** [comment]
There's a command, I think it's `report-emacs-bug`. The command will tell you what to write and where to send the email. It will also print a lot of information, which you don't have to send if you don't want to.

**Comment by joca-bt** [comment]
Yeah, I forgot. Thanks, I'll look into it tomorrow.

**Comment by Bruce-Connor** [comment]
It would be useful to try to reproduce this error from a clean emacs (an init file that does nothing except add Melpa to your archives). If the error doesn't happen then, that means it's being caused by one of your configurations.

**Comment by Bruce-Connor** [comment]
(If that's the case, it might still be considered an emacs bug. But it would be good to know what configuration caused it)

**Comment by joca-bt** [comment]
Both clean Emacs and clean Emacs with Paradox work fine, something else is interfering. I will analyse it later.

**Comment by Bruce-Connor** [comment]
Try to search you init files for instances of the terms `iso-latin', `encoding', or `utf-8'.

**Comment by joca-bt** [comment]
The error is in the mothership. It appears that ```emacs -q``` is not a reliable way of testing stuff.

**Comment by Bruce-Connor** [comment]
Ok, thanks for posting here.

**Comment by joca-bt** [comment]
Update: it's been solved.
