### ISSUE TITLE
run-hook-with-args: Symbol's value as variable is void: \.async

### ISSUE THREAD

**Issue by sprig** [Bruce-Connor/paradox#41]
Hello,

After updating paradox to "Version: 20150214.1342" from melpa and attempting to install a package in the asynchronous mode, I received the message in the title, and I now get the same message  whenever I try to install any package with paradox, including in non-async mode.

**Comment by Bruce-Connor** [comment]
Hi there, two questions:

1. What's your emacs version?
2. Do you have `let-alist' installed (it should be listed as a package in your Package Menu)?

**Comment by sprig** [comment]
Hello,

Version Reported: "GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2014-10-21 on builder10-9.porkrind.org"
I believe that this is the standard current version from http://emacsformacosx.com/.
I do have 'let-alist installed (at least (require 'let-alist) completes with no error).

**Comment by Bruce-Connor** [comment]
Thanks for the info.
It's very strange that you're getting this bug. I think it might be done installation issue with Emacs. 

Could you try just deleting paradox, then restarting emacs and reinstalling paradox?

**Comment by sprig** [comment]
Actually, I now grepped for \.async and found it in one of paradox's .elc files. I usually delete .elc files as I found them to often cause various problems (e.g. by getting left behind after an uninstall/upgrade of some package) that are really hard to diagnose.

Anyway, I thought I already deleted those but turns out that I didn't... Furthermore, turns out that deleting them and restarting emacs did the trick and now everything seems to work fine.

**Comment by alphapapa** [comment]
Just a note for anyone else who experiences this problem: I got the same `Symbol's value as variable is void: \.async` error, and I was going in circles trying to find out why.  Then I saw sprig's comment, so I recursively deleted all `.elc` files in my `elpa` directory, restarted Emacs, and the problem went away.

I think this "delete all `.elc`" files should now be part of the standard Emacs troubleshooting procedure, haha.

**Comment by alphapapa** [comment]
Well, I just ran into this same problem again, came here again, found this issue again, and did the same thing to fix it again.   Is there some kind of problem with elc files not being handled correctly when packages are upgraded?  I even deleted the obsolete versions of `async` and `paradox`, but I still had to go delete all the elc files manually.

**Comment by Malabarba** [comment]
@alphapapa You meant these files weren't present on the previous installation?
That points to a pretty serious issue. Whenever you install a package, there should always be the following files inside the installation directory:

- One `pkgname-pkg.el` file, with **no** `pkgname-pkg.elc` file.
- One `pkgname-autoloads.el` file, with **no** `pkgname-autoloads.elc` file.
- One `.elc` file for each `.el` file (except those two above).

Could you look around your other installde packages and see if they follow this?

**Comment by alphapapa** [comment]
Well, the sequence of events was something like this:

1.  Install updated async and paradox packages.
2.  Commit changed `elpa` directory to git.
3.  Restart Emacs.
4.  Notice a problem.
5.  Remove all versions of those packages.
6.  Reinstall latest versions of those packages.
7.  Notice problem seems to be fixed.
8.  Notice that those 4 files were listed by git as being modified.

So, according to git, those 4 files existed before I removed and reinstalled those versions of those packages, but after installing the packages the second time, those 4 files were different.  I don't know why that would be the case, but whatever happened, the problem seemed to then be fixed.

**Comment by Malabarba** [comment]
Could you check specifically what was different about them? What's the git diff?

**Comment by alphapapa** [comment]
Here is the git diff from the commit just after I reinstalled the packages to fix them.
```diff
diff --git a/emacs.d/elpa/async-20150812.209/async-autoloads.el b/emacs.d/elpa/async-20150812.209/async-autoloads.el
index b3de6b4..73d3d95 100644
--- a/emacs.d/elpa/async-20150812.209/async-autoloads.el
+++ b/emacs.d/elpa/async-20150812.209/async-autoloads.el
@@ -3,9 +3,8 @@
 ;;; Code:
 (add-to-list 'load-path (or (file-name-directory #$) (car load-path)))
 
-;;;### (autoloads nil "async" "../../../../../../.emacs.d/elpa/async-20150812.209/async.el"
-;;;;;;  "96ca1ef3cc5ee1401f3cffafffd1d9bf")
-;;; Generated autoloads from ../../../../../../.emacs.d/elpa/async-20150812.209/async.el
+;;;### (autoloads nil "async" "async.el" (21965 32791 824349 893000))
+;;; Generated autoloads from async.el
 
 (autoload 'async-start-process "async" "\
 Start the executable PROGRAM asynchronously.  See `async-start'.
@@ -69,9 +68,9 @@ returns nil.  It can still be useful, however, as an argument to
 
 ;;;***
 
-;;;### (autoloads nil "async-bytecomp" "../../../../../../.emacs.d/elpa/async-20150812.209/async-bytecomp.el"
-;;;;;;  "0bff4cfff65130b65179e8ea8ade8baa")
-;;; Generated autoloads from ../../../../../../.emacs.d/elpa/async-20150812.209/async-bytecomp.el
+;;;### (autoloads nil "async-bytecomp" "async-bytecomp.el" (21965
+;;;;;;  32791 780349 894000))
+;;; Generated autoloads from async-bytecomp.el
 
 (autoload 'async-byte-recompile-directory "async-bytecomp" "\
 Compile all *.el files in DIRECTORY asynchronously.
@@ -97,9 +96,9 @@ Async compilation of packages can be controlled by
 
 ;;;***
 
-;;;### (autoloads nil "dired-async" "../../../../../../.emacs.d/elpa/async-20150812.209/dired-async.el"
-;;;;;;  "a34489bc3f2debb23dd3740ada2665f0")
-;;; Generated autoloads from ../../../../../../.emacs.d/elpa/async-20150812.209/dired-async.el
+;;;### (autoloads nil "dired-async" "dired-async.el" (21965 32791
+;;;;;;  692349 895000))
+;;; Generated autoloads from dired-async.el
 
 (defvar dired-async-mode nil "\
 Non-nil if Dired-Async mode is enabled.
@@ -117,13 +116,8 @@ Do dired actions asynchronously.
 
 ;;;***
 
-;;;### (autoloads nil nil ("../../../../../../.emacs.d/elpa/async-20150812.209/async-autoloads.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/async-bytecomp.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/async-pkg.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/async.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/dired-async.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/smtpmail-async.el")
-;;;;;;  (21965 39849 67215 80000))
+;;;### (autoloads nil nil ("async-pkg.el" "smtpmail-async.el") (21965
+;;;;;;  32791 951473 41000))
 
 ;;;***
 
diff --git a/emacs.d/elpa/async-20150812.209/async-bytecomp.elc b/emacs.d/elpa/async-20150812.209/async-bytecomp.elc
index 228bfb4..50c7ea3 100644
Binary files a/emacs.d/elpa/async-20150812.209/async-bytecomp.elc and b/emacs.d/elpa/async-20150812.209/async-bytecomp.elc differ
diff --git a/emacs.d/elpa/paradox-20150812.732/paradox-autoloads.el b/emacs.d/elpa/paradox-20150812.732/paradox-autoloads.el
index 3d77bcc..c3e4520 100644
--- a/emacs.d/elpa/paradox-20150812.732/paradox-autoloads.el
+++ b/emacs.d/elpa/paradox-20150812.732/paradox-autoloads.el
@@ -3,9 +3,9 @@
 ;;; Code:
 (add-to-list 'load-path (or (file-name-directory #$) (car load-path)))
 
-;;;### (autoloads nil "paradox" "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox.el"
-;;;;;;  "ac69810f540901b0936616f4a9227bbf")
-;;; Generated autoloads from ../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox.el
+;;;### (autoloads nil "paradox" "paradox.el" (21965 32588 544352
+;;;;;;  46000))
+;;; Generated autoloads from paradox.el
 
 (autoload 'paradox-list-packages "paradox" "\
 Improved version of `package-list-packages'.  The heart of Paradox.
@@ -61,15 +61,9 @@ empty.  Passing a non-nil REFRESH argument forces this update.
 
 ;;;***
 
-;;;### (autoloads nil nil ("../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox-autoloads.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox-commit-list.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox-core.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox-execute.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox-github.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox-menu.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox-pkg.el"
-;;;;;;  "../../../../../../.emacs.d/elpa/paradox-20150812.732/paradox.el")
-;;;;;;  (21965 39875 713516 718000))
+;;;### (autoloads nil nil ("paradox-commit-list.el" "paradox-core.el"
+;;;;;;  "paradox-execute.el" "paradox-github.el" "paradox-menu.el"
+;;;;;;  "paradox-pkg.el") (21965 32588 791349 342000))
 
 ;;;***
 
diff --git a/emacs.d/elpa/paradox-20150812.732/paradox-execute.elc b/emacs.d/elpa/paradox-20150812.732/paradox-execute.elc
index 3d9b90f..7058e7d 100644
Binary files a/emacs.d/elpa/paradox-20150812.732/paradox-execute.elc and b/emacs.d/elpa/paradox-20150812.732/paradox-execute.elc differ
```

**Comment by Malabarba** [comment]
Ok, some of that looks ok, but other parts do catch my attention. Have a look at this snippet.

    -;;;### (autoloads nil nil ("async-pkg.el" "smtpmail-async.el") (21965
    -;;;;;;  32791 951473 41000))
    +;;;### (autoloads nil nil ("../../../../../../.emacs.d/elpa/async-20150812.209/async-autoloads.el"
    +;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/async-bytecomp.el"
    +;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/async-pkg.el"
    +;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/async.el"
    +;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/dired-async.el"
    +;;;;;;  "../../../../../../.emacs.d/elpa/async-20150812.209/smtpmail-async.el")
    +;;;;;;  (21965 39849 67215 80000))
    

- First of all, an entry like this one `"../../../../../../.emacs.d/elpa/async-20150812.209/async-pkg.el"` is not a sign of a healthy setup. :)
- More importantly, the fact that this entry was previously listed as `"async-pkg.el"` (which is the correct way) and now has changed to that `“../../...”` string shows that something changed which you're not aware of.

The two items above are a sign that something is changing that you're not aware of. However, they're not the most pressing issue. The most pressing issue is that there were many entries missing before that are present now. That's probably where your issue came from.

**Comment by alphapapa** [comment]
The levels of `../` come from my using `homesick` to manage my dotfiles:
```
$ ll ~/.emacs.d
lrwxrwxrwx 1 me me 46 Mar 13 15:56 /home/me/.emacs.d -> /home/me/.homesick/repos/emacs.d/home/.emacs.d/
```
So `~/.emacs.d` is a symlink to another directory.

I don't know where to place the blame (assuming I'm correct), but it seems like Emacs shouldn't be following these symlinks up to `~/` and then descending back into `~/.emacs.d`.  It should be using relative paths.

And I don't know why it would not use relative paths at first, and then use them when I reinstalled the package.

Could this be a bug in Emacs or in `package.el`?

**Comment by Malabarba** [comment]
> And I don't know why it would not use relative paths at first, and then use them when I reinstalled the package.

- How much time passed between the first installation and the reinstallation? 
- Were they both installed synchronously (or both asynchronously)?
- Are you following the Emacs master branch?

**Comment by alphapapa** [comment]
> How much time passed between the first installation and the reinstallation? 

Less than 2 hours.

> Were they both installed synchronously (or both asynchronously)?

I don't remember whether I used Paradox or `package-list` to update them.  Is that the same as your question?  :)  If not, I'm not sure what you mean.

> Are you following the Emacs master branch?

I'm running Emacs 24.4 on this system at the moment.
