### ISSUE TITLE
revert-buffer is expensive in paradox

### ISSUE THREAD

**Issue by sprig** [Bruce-Connor/paradox#42]
Hi,

when one presses 'g' in the package.el, revert-buffer is called. This appears to be a relatively free operation: no network traffic involved.

By contrast, in paradox this appears to be identical to the 'refresh' operation and takes a significant time to perform. I think it would be more appropriate if by pressing 'g', the current filter would remain and the install/delete selection would be cleared.

A workaround that I currently use is to 'filter' again by the current filter, but it seems counter intuitive.

**Comment by kaushalmodi** [comment]
+1

**Comment by Bruce-Connor** [comment]
Yes, that's a good point. I'll fix it on the next push

**Comment by Bruce-Connor** [comment]
Done.

**Comment by sprig** [comment]
Awesome, thanks!
