### ISSUE TITLE
Star counts have stopped updating

### ISSUE THREAD

**Issue by kaushalmodi** [Bruce-Connor/paradox#44]
I have noticed that the star counts are visible but have stopped updating for a while now.

Here's an example:

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6416173/28f55e12-be72-11e4-877b-bcabd8f7f55b.png)

**Comment by Bruce-Connor** [comment]
Ok, thanks for letting me know. The updater script probably froze, I'll check on it as soon as I can.

Meanwhile, could you let me know how you get this alternating line background?

**Comment by kaushalmodi** [comment]
Thanks. That's [`stripe-listify-buffer`](https://github.com/kaushalmodi/.emacs.d/blob/b62a81fde43a15605b28097a4474e612a1d8c006/setup-files/setup-stripe-buffer.el#L22) function from [`stripe-buffer`](https://github.com/sabof/stripe-buffer) package.

**Comment by Bruce-Connor** [comment]
Thanks. I've updated the counts manually, the machine where the script runs is being replaced. But auto-updates should be working again by monday.
