### ISSUE TITLE
Unable to validate token

### ISSUE THREAD

**Issue by msx** [Bruce-Connor/paradox#45]
Hello Bruce,
I'm unable to validate the token, I just keep receiving: Symbol's value as variable is void: {my token}.

Running Fedora 21 on my Emacs 24.4.1 machine. Wait, it's just the other way. Sadly.

Edit: here's the debug information, token is no longer available:
Debugger entered--Lisp error: (void-variable b5a96c24ab1d8d4ae0bba2c7f10496b038034cb2)
  (setq paradox-github-token b5a96c24ab1d8d4ae0bba2c7f10496b038034cb2)
  eval((setq paradox-github-token b5a96c24ab1d8d4ae0bba2c7f10496b038034cb2) nil)
  eval-expression((setq paradox-github-token b5a96c24ab1d8d4ae0bba2c7f10496b038034cb2) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

**Comment by Bruce-Connor** [comment]
Write it as a string instead. That is:

     (setq paradox-github-token "b5a96c24ab1d8d4ae0bba2c7f10496b038034cb2")

**Comment by msx** [comment]
Weee! I'm sure that's one of the most common errors Emacs n00bs incur in :)

Btw., an off-topic side note: I get the very same error message you describe in the Known Bugs section when updating the Marmalade repo - mental note: report it.

**Comment by Bruce-Connor** [comment]
Cool. Let me know if you figure out what's causing that message. I'm still not sure.

As for the token... You may want to invalidate this token an generate a new one, given that you've posted it publicly here. ;-)

**Comment by msx** [comment]
Already did so when I opened the ticket, thanks for the warning!
