### ISSUE TITLE
Github stars

### ISSUE THREAD

**Issue by pokesam94** [Bruce-Connor/paradox#46]
Star numbers will not display for any package and when attempting to star a package I get:
> Wrong type argument: number-or-marker-p, nil

EDIT: Upon inspection starring the package is successful regardless of above message however star numbers are indeed missing

Paradox version 2.0 and emacs version 24.4.1

I know I used to have no problem with stars and I only noticed this recently, possibly after upgrading to 24.4?

**Comment by xuchunyang** [comment]
Github stars will not displayed too from here.

I installed paradox from MELPA (and upgraded to latest version). My emacs was recently built from git master (the version number is 25.0.50.2).

**Comment by Bruce-Connor** [comment]
Thanks for reporting guys. I'll look into it later today. 
If anyone else has this problem, please voice in as well.

**Comment by Bruce-Connor** [comment]
Could you let me know the value of the variables paradox-display-star-count and paradox--user-starred-list?

**Comment by xuchunyang** [comment]
> Could you let me know the value of the variables paradox-display-star-count and paradox--user-starred-list?

t and nil.

I don't use the star/unstar actions, so the problem for me is just the star number is missing.

**Comment by pokesam94** [comment]
paradox-display-star-count --> t
paradox--user-starred-list   --> A list of all packages I have starred. It updates correctly when I star/unstar things.

**Comment by xuchunyang** [comment]
@Bruce-Connor I guess the star count should be stored in https://raw.githubusercontent.com/Bruce-Connor/paradox/data/data but it doesn't for now.

**Comment by Bruce-Connor** [comment]
Yes, something changed on github and it broke the counter script. I'll get to it as soon as possible.

**Comment by pokesam94** [comment]
Noticed you made the script change and looks like it's fixed! Nice job :+1:

**Comment by xuchunyang** [comment]
Works fine for me too.

**Comment by Bruce-Connor** [comment]
Great, thanks again for reporting!
