### ISSUE TITLE
asynchronous execution fails

### ISSUE THREAD

**Issue by genovese** [Bruce-Connor/paradox#50]
Paradox is very nice; a real improvement.
I've been using it for a while quite happily.

One issue that has arisen is during asynchronous
execution.  I get the following messages each time,
whether on install, delete, or both.

    Execute in the background? (see `paradox-execute-asynchronously') (y or n) y
    error in process sentinel: if: Wrong type argument: listp, \.\.\.
    error in process sentinel: Wrong type argument: listp, \.\.\.

I haven't had a chance to track the problem any further.

For reference, I'm running GNU Emacs 24.4.1 on Mac OS X 10.7.5.

Thanks

**Comment by Bruce-Connor** [comment]
Hey there, thanks for reporting. 
This looks similar to #37. Unfortunately, that issue was closed without an answer because the user couldn't reproduce it anymore.

I have suspicions it may be an `async` bug, but it can also be something in your configuration.

What are the values of print-level and print-length for you?

**Comment by genovese** [comment]
print-level is 8,  print-length is 1024.

Let me know what other information you need.

Next time I try it,  I can also try to use a minimal configuration to see
what happens.

Best, Chris

**Comment by Bruce-Connor** [comment]
Ok. Setting both of these variables to nil should definitely fix your problem.

Try it and let me know.

**Comment by Bruce-Connor** [comment]
Hi @genovese 
Did you get a chance to try it?
If you're unsure, here's what's needed:

    (setq print-level nil
          print-length nil)

**Comment by genovese** [comment]
My apologies for the delay. It's been a challenging few days.
I know what to do, and I will try it tonight.

Best, Chris

**Comment by genovese** [comment]
It worked without a problem after setting print-level and print-length to
nil.

Thanks, Chris
