### ISSUE TITLE
Paradox installing some packages twice when paradox-lines-per-entry is set to 2

### ISSUE THREAD

**Issue by lesharris** [Bruce-Connor/paradox#53]
Here's an example of my most recent 'upgrade packages' operation:
Installed:
  yasnippet    20150318.348
  yasnippet    20150318.348
  use-package  20150318.1856
  use-package  20150318.1856
  go-mode      20150318.1134
  go-mode      20150318.1134
  git-gutter   20150318.804
  git-gutter   20150318.804
  evil         20150318.1515
  ace-link     20150318.1256

Deleted:
  helm         20150317.538
  go-mode      20150226.1606
  yasnippet    20150212.240
  use-package  20150317.950
  git-gutter   20150106.659
  evil         20150313.1208
  ace-link     20150220.1134

I can't seem to find any definitive pattern to why some packages aren't installed twice.  In the pre-execution summary screen the "I" mark for 'Install' is next to all lines not just the package name which I SUSPECT has something to do with this.

Any diagnostic I can provide gratefully given.

**Comment by Bruce-Connor** [comment]
Oh, that's a pretty nasty bug. Fortunately, it looks pretty straightforward. Thanks for filing this, I'll fix as soon as possible.

**Comment by Bruce-Connor** [comment]
Should be fixed now. Let me know if it works or if you run into any problems!

**Comment by lesharris** [comment]
Works a treat. Thanks a bunch Bruce.
