### ISSUE TITLE
Package list is not updated after action taken

### ISSUE THREAD

**Issue by alphapapa** [Bruce-Connor/paradox#54]
I just used Paradox to delete an old package, and after the removal finished, the top window still shows the single package marked for deletion, as if nothing was done.  But the package was removed successfully.

So I pressed `g` to update the window, and then the package disappeared.  But that's still not very helpful, because I wanted to see the list of packages again.  So I pressed `q` and the window was closed.  Still not what I wanted.  So I ran `paradox-list-packages` again...and now I have to wait while it queries GitHub and downloads all the package lists again.  All I wanted was to return to the package list.

BTW, am I nuts, or is there no way to prevent Emacs/package/paradox/whatever from redownloading all the package lists every time I run `list-packages`, other than running `package-list-packages-no-fetch`?  I mean, there ought to be a default limit of refreshing it no more often than every hour or something, because downloading it all every time I open the package list is really wasteful, both of server resources and user time.  It doesn't even seem to use HTTP if-modified-since, because it seems to actually redownload the package lists every time.

P.S.  Ok, I just discovered by accident that the package list is actually there, but the window is scrolled to the bottom of the buffer, so when I press `g` and it removes the line with the previously-marked-but-now-deleted package, the window appears empty.  If I scroll back up, the package list is there.  Now I feel a little silly, haha.  But this is still quite unintuitive.  :)

**Comment by Bruce-Connor** [comment]
Ok, there are several things going on here.

> I just used Paradox to delete an old package, and after the removal finished, the top window still shows the single package marked for deletion, as if nothing was done. But the package was removed successfully.

I think I noticed something like that recently. Be it a window-scrolling thing or a buffer-contents thing, if it's happening it's a bug, so I'll look into it.

> BTW, am I nuts, or is there no way to prevent Emacs/package/paradox/whatever from redownloading all the package lists every time I run list-packages, other than running package-list-packages-no-fetch? I mean, there ought to be a default limit of refreshing it no more often than every hour or something, because downloading it all every time I open the package list is really wasteful, both of server resources and user time. It doesn't even seem to use HTTP if-modified-since, because it seems to actually redownload the package lists every time.

- If you're inside the package menu, `g` should not fetch anything.
- If you're inside a filter, `g` will refresh the filter and `f c` will clear the filter (go back to the full menu), and *neither* of them should fetch anything.
- If you're outside the package menu, invoke `paradox-list-packages` with a prefix argument will prevent fetching (the same is true for `package.el`).

> P.S. Ok, I just discovered by accident that the package list is actually there, but the window is scrolled to the bottom of the buffer, so when I press g and it removes the line with the previously-marked-but-now-deleted package, the window appears empty. If I scroll back up, the package list is there. Now I feel a little silly, haha. But this is still quite unintuitive. :)

Yes, the package menu should do something to avoid that.

**Comment by alphapapa** [comment]
Thanks for the tip about the prefix argument.  Do you think there's any merit to the idea of having a default interval between downloading the package lists automatically?  When I'm messing with packages, I tend to do so in spurts, and so I end up closing and reopening the package list frequently.  It would be handy if I didn't have to remember to use a prefix every time.

**Comment by Bruce-Connor** [comment]
Yes, I think there is merit, but that's something to be handled directly by package.el, I think.
It's been mentioned before in the emacs-devel list, but didn't lead anywhere.
But this whole issue will probably become moot once package.el does async refreshing.

**Comment by alphapapa** [comment]
Ok, thanks.  :)

**Comment by kaushalmodi** [comment]
I am probably seeing the same thing: The package updates have finished as shown in the Paradox Report but the Paradox buffer still stuck in "Executing Transaction". As OP mentioned, I need to quit this buffer and restart paradox to see the updated package list.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/6802062/8f38851a-d203-11e4-8ff9-eeb85c0ccdf3.png)

Emacs 25.x

**Comment by Bruce-Connor** [comment]
Should be fixed now. Let me know if it works!
