### ISSUE TITLE
(wrong-number-of-arguments (1 . 1) 2) when installing/upgrading packages

### ISSUE THREAD

**Issue by halbtuerke** [Bruce-Connor/paradox#56]
Hi,

I just tried upgrading packages with Paradox and got the following errors in `*Paradox Report*`:

```elisp
Package transaction finished. Mon Mar 23 12:02:45 2015
Errors:
  (wrong-number-of-arguments (1 . 1) 2)
(wrong-number-of-arguments (1 . 1) 2)
(wrong-number-of-arguments (1 . 1) 2)
(wrong-number-of-arguments (1 . 1) 2)
(wrong-number-of-arguments (1 . 1) 2)
(wrong-number-of-arguments (1 . 1) 2)
(wrong-number-of-arguments (1 . 1) 2)
(wrong-number-of-arguments (1 . 1) 2)
```

I then tried to install those packages through Paradox and got the same error messages. Installing via `package-install` is working though.

Versions:

- Paradox 20150320.350
- Emacs 25.0.50.1 (x86_64-apple-darwin14.1.0, NS appkit-1344.72 Version 10.10.2 (Build 14C109)) of 2015-01-31"

If you need any additional information please let me know.

Thanks in advance

**Comment by Bruce-Connor** [comment]
Since you're on Emacs 25, could you try again with the latest build? Package.el has been changing a lot in the development builds, and it's possible you're left midway through a change.

**Comment by halbtuerke** [comment]
I'm now on GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.1.0, NS appkit-1344.72 Version 10.10.2 (Build 14C1514)) of 2015-03-23 and upgrading / installing works again.

**Comment by Bruce-Connor** [comment]
Glad it's solved.
